# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="${license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/yanny7/advancedlootinfo/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="alicompat" #mandatory
# The version number of the mod
version="${alicompat_version}" #mandatory
# A display name for the mod
displayName="${alicompat_mod_name}" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/yanny7/advancedlootinfo" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional
logoBlur = false
# A text field displayed in the mod UI
authors="${mod_author}" #optional
# Display Test controls the display for your mod in the server connection screen
displayTest="IGNORE_ALL_VERSION"

# The description text for the mod (multi line!) (#mandatory)
description='''${alicompat_description}'''

[[dependencies.alicompat]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="${forge_version_range}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

[[dependencies.alicompat]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.alicompat]]
modId="aci"
mandatory=true
versionRange="${aci_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.alicompat]]
modId="ali"
mandatory=true
versionRange="${alicompat_ali_version_range}"
ordering="AFTER"
side="BOTH"
