plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":ali:common").loom.accessWidenerPath

    runs {
        datagen {
            inherit client
            name "Minecraft Data"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":ali:fabric").file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=${ali_mod_id}"

            runDir "build/datagen"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    common(project(path: ":aci:common")) { transitive false }
    runtimeOnly project(":aci:fabric")

    project.ext.commonProjects.each { p ->
        common(project(path: p)) { transitive false }
        shadowCommon(project(path: p, configuration: "transformProductionFabric")) { transitive false }
    }

    // LootJS
//    compileOnly "curse.maven:kubejs-238086:5853321"
//    compileOnly "curse.maven:rhino-416294:6186969"
//    compileOnly "curse.maven:architectury-api-419699:5137936"
//    compileOnly "curse.maven:lootjs-570630:5404564"
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from(zipTree(jar.archiveFile))     // Unpack jar output (preserves Loom modifications)

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null           // shadowJar becomes the main artifact
    from rootProject.file("LICENSE")
}

sourcesJar {
    def commonSources = project(":ali:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
