plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":ali:common").loom.accessWidenerPath

    runs {
        datagen {
            inherit client
            name "Minecraft Data"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":ali:fabric").file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=${ali_mod_id}"

            runDir "build/datagen"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    common(project(path: ":aci:common", configuration: "namedElements")) { transitive false }
    runtimeOnly project(path: ":aci:fabric", configuration: "namedElements")

    project.ext.commonProjects.each { p ->
        common(project(path: p, configuration: "namedElements")) { transitive false }
        shadowCommon(project(path: p, configuration: "transformProductionFabric")) { transitive false }
    }

    // LootJS
//    modCompileOnly "curse.maven:kubejs-238086:5853321"
//    modCompileOnly "curse.maven:rhino-416294:6186969"
//    modCompileOnly "curse.maven:architectury-api-419699:5137936"
//    modCompileOnly "curse.maven:lootjs-570630:5404564"
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":ali:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}