plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":ali:common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "ali.mixins.json"
        mixinConfig "ali.forge.mixins.json"

        if (emi_enabled == "true" && forge_emi_enabled == "true") {
            mixinConfig "ali.emi.mixins.json"
        }

        if (lootjs_enabled == "true" && forge_lootjs_enabled == "true") {
            mixinConfig "ali.lootjs.mixins.json"
        }
    }

    mixin {
        defaultRefmapName = "ali.forge.refmap.json"
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "${ali_mod_id}"
            programArgs "--output", "${file('src/main/generated/')}"
            programArgs "--existing", "${file("src/main/resources").absolutePath}"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    common(project(path: ":aci:common", configuration: "namedElements")) { transitive false }
    runtimeOnly project(path: ":aci:forge", configuration: "namedElements")

    project.ext.commonProjects.each { p ->
        common(project(path: p, configuration: "namedElements")) { transitive false }
        shadowCommon(project(path: p, configuration: "transformProductionForge")) { transitive false }
    }

    // LootJS
//    modCompileOnly fg.deobf("curse.maven:kubejs-238086:5853326")
//    modCompileOnly fg.deobf("curse.maven:rhino-416294:6186971")
//    modCompileOnly fg.deobf("curse.maven:lootjs-570630:5404565")
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

sourcesJar {
    def commonSources = project(":ali:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}