package com.yanny.emi_loot_addon.datagen;

import com.yanny.emi_loot_addon.EmiLootMod;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

class EmiLanguageProvider extends LanguageProvider {
    public EmiLanguageProvider(PackOutput output, String locale) {
        super(output, EmiLootMod.MOD_ID, locale);
    }

    @Override
    protected void addTranslations() {
        add("emi.category.emi_loot_addon.block_loot", "Block Drops");
        add("emi.category.emi_loot_addon.entity_loot", "Entity Drops");
        add("emi.category.emi_loot_addon.gameplay_loot", "Gameplay Drops");

        add("emi.description.emi_loot_addon.chance", "Chance: %s");
        add("emi.description.emi_loot_addon.chance_rolls", "Chance: [%s] %s");
        add("emi.description.emi_loot_addon.chance_bonus", "%s (%s %s)");
        add("emi.description.emi_loot_addon.count", "Count: %s");
        add("emi.description.emi_loot_addon.count_bonus", "%s (%s %s)");

        add("emi.type.emi_loot_addon.condition.all_of", "All must pass:");
        add("emi.type.emi_loot_addon.condition.any_of", "Any of:");
        add("emi.type.emi_loot_addon.condition.inverted", "Inverted:");
        add("emi.type.emi_loot_addon.condition.survives_explosion", "Must survive explosion");
        add("emi.type.emi_loot_addon.condition.killed_by_player", "Must be killed by player");
        add("emi.type.emi_loot_addon.condition.explosion_decay", "Explosion decreases amount");
        add("emi.type.emi_loot_addon.condition.entity_properties", "Entity Properties:");
        add("emi.type.emi_loot_addon.condition.entity_scores", "Entity Scores:");
        add("emi.type.emi_loot_addon.condition.block_state_property", "Block State Property:");
        add("emi.type.emi_loot_addon.condition.match_tool", "Match Tool:");
        add("emi.type.emi_loot_addon.condition.damage_source_properties", "Damage Source Properties:");
        add("emi.type.emi_loot_addon.condition.location_check", "Location Check:");
        add("emi.type.emi_loot_addon.condition.weather_check", "Weather Check:");
        add("emi.type.emi_loot_addon.condition.reference", "Reference: %s");
        add("emi.type.emi_loot_addon.condition.time_check", "Time Check:");
        add("emi.type.emi_loot_addon.condition.value_check", "Value Check:");
        add("emi.type.emi_loot_addon.condition.loot_condition_type", "Can Tool Perform Action: %s");

        add("emi.type.emi_loot_addon.function.enchant_with_levels", "Enchanted With Levels:");
        add("emi.type.emi_loot_addon.function.enchant_randomly", "Enchanted Randomly");
        add("emi.type.emi_loot_addon.function.set_enchantments", "Set Enchantments:");
        add("emi.type.emi_loot_addon.function.set_nbt", "Set Nbt:");
        add("emi.type.emi_loot_addon.function.set_damage", "Set Damage:");
        add("emi.type.emi_loot_addon.function.set_attributes", "Set Attributes:");
        add("emi.type.emi_loot_addon.function.set_name", "Set Name:");
        add("emi.type.emi_loot_addon.function.exploration_map", "Exploration Map:");
        add("emi.type.emi_loot_addon.function.set_stew_effect", "Set Stew Effect:");
        add("emi.type.emi_loot_addon.function.copy_name", "Copies Name:");
        add("emi.type.emi_loot_addon.function.set_contents", "Set Contents:");
        add("emi.type.emi_loot_addon.function.set_loot_table", "Set Loot Table:");
        add("emi.type.emi_loot_addon.function.explosion_decay", "Explosion Decay");
        add("emi.type.emi_loot_addon.function.set_lore", "Set Lore:");
        add("emi.type.emi_loot_addon.function.fill_player_head", "Fill Player Head:");
        add("emi.type.emi_loot_addon.function.copy_nbt", "Copies Nbt");
        add("emi.type.emi_loot_addon.function.copy_state", "Copy State:");
        add("emi.type.emi_loot_addon.function.set_banner_pattern", "Set Banner Pattern:");
        add("emi.type.emi_loot_addon.function.set_potion", "Set Potion:");
        add("emi.type.emi_loot_addon.function.set_instrument", "Set Instrument:");
        add("emi.type.emi_loot_addon.function.reference", "Reference:");

        add("emi.enum.target.this", "This entity");
        add("emi.enum.target.killer", "Killer");
        add("emi.enum.target.direct_killer", "Directly killed by");
        add("emi.enum.target.killer_player", "Last damaged by player");

        add("emi.enum.name_source.this", "This entity");
        add("emi.enum.name_source.killer", "Killer");
        add("emi.enum.name_source.killer_player", "Last damaged by player");
        add("emi.enum.name_source.block_entity", "Block Entity");

        add("emi.property.condition.unknown", "Unknown Condition: %s");
        add("emi.property.condition.predicate.target", "Target: %s");
        add("emi.property.condition.predicate.entity_type", "Entity Type:");
        add("emi.property.condition.predicate.dist_to_player", "Distance:");
        add("emi.property.condition.predicate.location", "Location:");
        add("emi.property.condition.predicate.stepping_on_location", "Stepping on Location:");
        add("emi.property.condition.predicate.effect", "Effects:");
        add("emi.property.condition.predicate.nbt", "NBT: %s");
        add("emi.property.condition.predicate.flags", "Flags:");
        add("emi.property.condition.predicate.equipment", "Equipment:");
        add("emi.property.condition.predicate.entity_sub_type", "Entity Subtype: %s");
        add("emi.property.condition.predicate.vehicle", "Vehicle:");
        add("emi.property.condition.predicate.passenger", "Passenger:");
        add("emi.property.condition.predicate.targeted_entity", "Targeted Entity:");
        add("emi.property.condition.predicate.team", "Team: %s");
        add("emi.property.condition.dist_predicate.horizontal", "Hor.: %s");
        add("emi.property.condition.dist_predicate.absolute", "Abs.: %s");
        add("emi.property.condition.dist_predicate.x", "X: %s");
        add("emi.property.condition.dist_predicate.y", "Y: %s");
        add("emi.property.condition.dist_predicate.z", "Z: %s");
        add("emi.property.condition.location.x", "X: %s");
        add("emi.property.condition.location.y", "Y: %s");
        add("emi.property.condition.location.z", "Z: %s");
        add("emi.property.condition.location.biome", "Biome: %s");
        add("emi.property.condition.location.structure", "Structure: %s");
        add("emi.property.condition.location.dimension", "Dimension: %s");
        add("emi.property.condition.location.smokey", "Above Campfire: %s");
        add("emi.property.condition.location.light", "Light Level: %s");
        add("emi.property.condition.location.block", "Block:");
        add("emi.property.condition.location.fluid", "Fluid:");
        add("emi.property.condition.block.tag", "Tag: %s");
        add("emi.property.condition.block.blocks", "Blocks:");
        add("emi.property.condition.block.state", "Block States:");
        add("emi.property.condition.block.nbt", "NBT: %s");
        add("emi.property.condition.fluid.tag", "Tag: %s");
        add("emi.property.condition.fluid.fluid", "Fluid: %s");
        add("emi.property.condition.fluid.state", "Fluid States:");
        add("emi.property.condition.effect.amplifier", "Amplifier: %s");
        add("emi.property.condition.effect.duration", "Duration: %s");
        add("emi.property.condition.effect.ambient", "Ambient: %s");
        add("emi.property.condition.effect.visible", "Visible: %s");
        add("emi.property.condition.flags.on_fire", "On Fire: %s");
        add("emi.property.condition.flags.is_baby", "Is Baby: %s");
        add("emi.property.condition.flags.is_crouching", "Is Crouching: %s");
        add("emi.property.condition.flags.is_sprinting", "Is Sprinting: %s");
        add("emi.property.condition.flags.is_swimming", "Is Swimming: %s");
        add("emi.property.condition.equipment.head", "Head:");
        add("emi.property.condition.equipment.chest", "Chest:");
        add("emi.property.condition.equipment.legs", "Legs:");
        add("emi.property.condition.equipment.feet", "Feet:");
        add("emi.property.condition.equipment.mainhand", "Mainhand:");
        add("emi.property.condition.equipment.offhand", "Offhand:");
        add("emi.property.condition.item.tag", "Tag: %s");
        add("emi.property.condition.item.items", "Items:");
        add("emi.property.condition.item.count", "Count: %s");
        add("emi.property.condition.item.durability", "Durability: %s");
        add("emi.property.condition.item.enchantment", "Enchantment:");
        add("emi.property.condition.item.stored_enchantment", "Stored Enchantment:");
        add("emi.property.condition.item.potion", "Potion:");
        add("emi.property.condition.item.nbt", "NBT: %s");
        add("emi.property.condition.enchantment.level", "Level: %s");
        add("emi.property.condition.sub_entity.variant", "Variant: %s");
        add("emi.property.condition.sub_entity.blocks_on_fire", "Blocks on Fire: %s");
        add("emi.property.condition.sub_entity.stuck_entity", "Stuck Entity:");
        add("emi.property.condition.sub_entity.in_open_water", "In Open Water: %s");
        add("emi.property.condition.sub_entity.level", "Level: %s");
        add("emi.property.condition.sub_entity.game_type", "Game Type: %s");
        add("emi.property.condition.sub_entity.stats", "Stats:");
        add("emi.property.condition.sub_entity.recipes", "Recipes:");
        add("emi.property.condition.sub_entity.advancements", "Advancements:");
        add("emi.property.condition.sub_entity.advancement.done", "Done: %s");
        add("emi.property.condition.sub_entity.size", "Size: %s");
        add("emi.property.condition.scores.score", "Score:");
        add("emi.property.condition.damage_source.direct_entity", "Direct Entity:");
        add("emi.property.condition.damage_source.source_entity", "Source Entity:");
        add("emi.property.condition.damage_source.tags", "Tags:");
        add("emi.property.condition.location_check.location", "Location:");
        add("emi.property.condition.location_check.offset", "Offset:");
        add("emi.property.condition.location_check.x", "X: %s");
        add("emi.property.condition.location_check.y", "Y: %s");
        add("emi.property.condition.location_check.z", "Z: %s");
        add("emi.property.condition.weather_check.is_raining", "Is Raining: %s");
        add("emi.property.condition.weather_check.is_thundering", "Is Thundering: %s");
        add("emi.property.condition.time_check.period", "Period: %s");
        add("emi.property.condition.time_check.value", "Value: %s");
        add("emi.property.condition.value_check.provider", "Provider: %s");
        add("emi.property.condition.value_check.range", "Range: %s");
        add("emi.property.function.conditions", "Conditions:");

        add("emi.property.function.unknown", "Unknown Function: %s");
        add("emi.property.function.enchant_with_levels.levels", "Levels: %s");
        add("emi.property.function.enchant_with_levels.treasure", "Treasure: %s");
        add("emi.property.function.enchant_randomly.enchantments", "Available Enchantments:");
        add("emi.property.function.set_enchantments.enchantments", "Available Enchantments:");
        add("emi.property.function.set_enchantments.enchantment", "%s [%s]");
        add("emi.property.function.set_enchantments.add", "Add: %s");
        add("emi.property.function.set_damage.damage", "Damage: %s");
        add("emi.property.function.set_damage.add", "Add: %s");
        add("emi.property.function.set_attributes.name", "Name: %s");
        add("emi.property.function.set_attributes.attribute", "Attribute: %s");
        add("emi.property.function.set_attributes.operation", "Operation: %s");
        add("emi.property.function.set_attributes.amount", "Amount: %s");
        add("emi.property.function.set_attributes.id", "Id: %s");
        add("emi.property.function.set_attributes.slots", "Slots:");
        add("emi.property.function.set_name.name", "Name: %s");
        add("emi.property.function.set_name.resolution_context", "Entity: %s");
        add("emi.property.function.exploration_map.destination", "Destination: %s");
        add("emi.property.function.exploration_map.map_decoration", "Map Decoration: %s");
        add("emi.property.function.exploration_map.zoom", "Zoom: %s");
        add("emi.property.function.exploration_map.search_radius", "Search Radius: %s");
        add("emi.property.function.exploration_map.skip_known_structures", "Skip Known Structures: %s");
        add("emi.property.function.set_stew_effect.effect", "%s: %s");
        add("emi.property.function.copy_name.source", "Source: %s");
        add("emi.property.function.set_contents.type", "Type: %s");
        add("emi.property.function.set_loot_table.name", "Name: %s");
        add("emi.property.function.set_loot_table.seed", "Seed: %s");
        add("emi.property.function.set_loot_table.type", "Type: %s");
        add("emi.property.function.set_lore.replace", "Replace: %s");
        add("emi.property.function.set_lore.resolution_context", "Entity: %s");
        add("emi.property.function.set_lore.lore", "Lore:");
        add("emi.property.function.fill_player_head.target", "Target: %s");
        add("emi.property.function.copy_state.block", "Block: %s");
        add("emi.property.function.copy_state.properties", "Properties:");
        add("emi.property.function.set_banner_pattern.append", "Append: %s");
        add("emi.property.function.set_banner_pattern.patterns", "Patterns:");
        add("emi.property.function.set_banner_pattern.color", "Color: %s");
        add("emi.property.function.set_potion.name", "Name: %s");
        add("emi.property.function.set_potion.effects", "Effects:");
        add("emi.property.function.set_instrument.options", "Options: %s");
        add("emi.property.function.reference.name", "Name: %s");

        add("emi.util.emi_loot_addon.two_values", "%s%s");
        add("emi.util.emi_loot_addon.two_values_with_space", "%s %s");
        add("emi.util.emi_loot_addon.pad.1", "  ->");
        add("emi.util.emi_loot_addon.pad.2", "    ->");
        add("emi.util.emi_loot_addon.pad.3", "      ->");
        add("emi.util.emi_loot_addon.pad.4", "        ->");
        add("emi.util.emi_loot_addon.pad.5", "          ->");
        add("emi.util.emi_loot_addon.pad.6", "            ->");
        add("emi.util.emi_loot_addon.pad.7", "              ->");
        add("emi.util.emi_loot_addon.pad.8", "                ->");
        add("emi.util.emi_loot_addon.key_value", "%s: %s");

        add("emi.debug.rolls", "Raw Rolls: %s");
        add("emi.debug.bonus_rolls", "Raw Bonus Rolls: %s");
        add("emi.debug.chance", "Raw Chance: %s");
        add("emi.debug.random_chance", "Random Chance: %s");
        add("emi.debug.set_count", "Set Count: %s (Add: %s)");
        add("emi.debug.limit_count", "Limit Count: [%s .. %s]");
    }
}
