modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/yanny7/advancedlootinfo/issues" #optional

[[mods]] #mandatory
modId = "alicompat" #mandatory
version = "${alicompat_version}" #mandatory
displayName = "${alicompat_mod_name}" #mandatory
displayTest = "IGNORE_ALL_VERSION"
displayURL="https://github.com/yanny7/advancedlootinfo" #optional (displayed in the mod UI)
logoFile="logo.png" #optional
logoBlur = false
authors = "${mod_author}" #optional
description = '''${alicompat_description}''' #mandatory (Supports multiline text)

[[dependencies.alicompat]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${neoforge_version_range}" #mandatory
ordering = "AFTER" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.alicompat]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${minecraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.alicompat]]
modId="aci"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange="${aci_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.alicompat]]
modId="ali"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange="${alicompat_ali_version_range}"
ordering="AFTER"
side="BOTH"
