plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":ali:common").loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named("shadowJar"), "ali.accesswidener")
    }

    mixin {
        defaultRefmapName = "ali.neoforge.refmap.json"
    }

    runs {
        data {
            clientData()
            programArgs "--all", "--mod", "${ali_mod_id}"
            programArgs "--output", "${file('src/main/generated/')}"
            programArgs "--existing", "${file("src/main/resources").absolutePath}"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"
    common(project(path: ":aci:common")) { transitive false }
    runtimeOnly project(":aci:neoforge")

    project.ext.commonProjects.each { p ->
        common(project(path: p)) { transitive false }
        shadowCommon(project(path: p, configuration: "transformProductionNeoForge")) { transitive false }
    }

    // LootJS
//    compileOnly "curse.maven:kubejs-238086:5810100"
//    compileOnly "curse.maven:rhino-416294:6184623"
//    compileOnly "curse.maven:lootjs-570630:6792267"
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from(zipTree(jar.archiveFile))     // Unpack jar output (preserves Loom modifications)

    exclude "fabric.mod.json"
    exclude "ali.accessWidener"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null           // shadowJar becomes the main artifact
    from rootProject.file("LICENSE")
}

sourcesJar {
    def commonSources = project(":ali:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
