plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":ali:common").loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named("remapJar"), "ali.accesswidener")
    }

    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "ali.neoforge.refmap.json"
    }

    runs {
        data {
            clientData()
            programArgs "--all", "--mod", "${ali_mod_id}"
            programArgs "--output", "${file('src/main/generated/')}"
            programArgs "--existing", "${file("src/main/resources").absolutePath}"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${neoforge_version}"
    common(project(path: ":aci:common", configuration: "namedElements")) { transitive false }
    runtimeOnly project(path: ":aci:neoforge", configuration: "namedElements")

    project.ext.commonProjects.each { p ->
        common(project(path: p, configuration: "namedElements")) { transitive false }
        shadowCommon(project(path: p, configuration: "transformProductionNeoForge")) { transitive false }
    }

    // LootJS
    modCompileOnly "curse.maven:kubejs-238086:5810100"
    modCompileOnly "curse.maven:rhino-416294:6184623"
    modCompileOnly "curse.maven:lootjs-570630:6792267"
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

sourcesJar {
    def commonSources = project(":ali:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}