package com.yanny.ali.datagen;

import java.util.HashMap;
import java.util.Map;

public class LanguageHolder {
    public static final Map<String, String> TRANSLATION_MAP = new HashMap<>();

    static {
        TRANSLATION_MAP.put("emi.category.ali.block_loot", "Block Drops");
        TRANSLATION_MAP.put("emi.category.ali.plant_loot", "Plant Drops");
        TRANSLATION_MAP.put("emi.category.ali.entity_loot", "Entity Drops");
        TRANSLATION_MAP.put("emi.category.ali.chest_loot", "Chest Loot");
        TRANSLATION_MAP.put("emi.category.ali.fishing_loot", "Fishing Loot");
        TRANSLATION_MAP.put("emi.category.ali.archaeology_loot", "Archaeology Loot");
        TRANSLATION_MAP.put("emi.category.ali.hero_loot", "Hero of the Village Loot");
        TRANSLATION_MAP.put("emi.category.ali.gameplay_loot", "Gameplay Loot");

        TRANSLATION_MAP.put("ali.description.rolls", "Rolls: %s");
        TRANSLATION_MAP.put("ali.description.chance", "Chance: %s");
        TRANSLATION_MAP.put("ali.description.chance_bonus", "%s (%s %s)");
        TRANSLATION_MAP.put("ali.description.count", "Count: %s");
        TRANSLATION_MAP.put("ali.description.count_bonus", "%s (%s %s)");
        TRANSLATION_MAP.put("ali.description.quality", "Quality: %s");
        TRANSLATION_MAP.put("ali.description.weight", "Weight: %s");

        TRANSLATION_MAP.put("ali.type.condition.all_of", "All must pass:");
        TRANSLATION_MAP.put("ali.type.condition.any_of", "Any of:");
        TRANSLATION_MAP.put("ali.type.condition.inverted", "Inverted:");
        TRANSLATION_MAP.put("ali.type.condition.survives_explosion", "Must survive explosion");
        TRANSLATION_MAP.put("ali.type.condition.random_chance", "Random Chance:");
        TRANSLATION_MAP.put("ali.type.condition.random_chance_with_looting", "Random Chance With Looting:");
        TRANSLATION_MAP.put("ali.type.condition.table_bonus", "Table Bonus:");
        TRANSLATION_MAP.put("ali.type.condition.killed_by_player", "Must be killed by player");
        TRANSLATION_MAP.put("ali.type.condition.explosion_decay", "Explosion decreases amount");
        TRANSLATION_MAP.put("ali.type.condition.entity_properties", "Entity Properties:");
        TRANSLATION_MAP.put("ali.type.condition.entity_scores", "Entity Scores:");
        TRANSLATION_MAP.put("ali.type.condition.block_state_property", "Block State Property:");
        TRANSLATION_MAP.put("ali.type.condition.match_tool", "Match Tool:");
        TRANSLATION_MAP.put("ali.type.condition.damage_source_properties", "Damage Source Properties:");
        TRANSLATION_MAP.put("ali.type.condition.location_check", "Location Check:");
        TRANSLATION_MAP.put("ali.type.condition.weather_check", "Weather Check:");
        TRANSLATION_MAP.put("ali.type.condition.reference", "Reference: %s");
        TRANSLATION_MAP.put("ali.type.condition.time_check", "Time Check:");
        TRANSLATION_MAP.put("ali.type.condition.value_check", "Value Check:");
        TRANSLATION_MAP.put("ali.type.condition.loot_condition_type", "Can Tool Perform Action: %s");

        TRANSLATION_MAP.put("ali.type.function.conditional", "Conditions:");
        TRANSLATION_MAP.put("ali.type.function.limit_count", "Limit Count:");
        TRANSLATION_MAP.put("ali.type.function.furnace_smelt", "Use Smelting Recipe On Item");
        TRANSLATION_MAP.put("ali.type.function.apply_bonus", "Apply Bonus:");
        TRANSLATION_MAP.put("ali.type.function.looting_enchant", "Looting Enchant:");
        TRANSLATION_MAP.put("ali.type.function.set_count", "Set Count:");
        TRANSLATION_MAP.put("ali.type.function.enchant_with_levels", "Enchanted With Levels:");
        TRANSLATION_MAP.put("ali.type.function.enchant_randomly", "Enchanted Randomly");
        TRANSLATION_MAP.put("ali.type.function.set_enchantments", "Set Enchantments:");
        TRANSLATION_MAP.put("ali.type.function.set_damage", "Set Damage:");
        TRANSLATION_MAP.put("ali.type.function.set_attributes", "Set Attributes:");
        TRANSLATION_MAP.put("ali.type.function.set_name", "Set Name:");
        TRANSLATION_MAP.put("ali.type.function.exploration_map", "Exploration Map:");
        TRANSLATION_MAP.put("ali.type.function.set_stew_effect", "Set Stew Effect:");
        TRANSLATION_MAP.put("ali.type.function.copy_name", "Copies Name:");
        TRANSLATION_MAP.put("ali.type.function.set_contents", "Set Contents:");
        TRANSLATION_MAP.put("ali.type.function.set_loot_table", "Set Loot Table:");
        TRANSLATION_MAP.put("ali.type.function.explosion_decay", "Explosion Decay");
        TRANSLATION_MAP.put("ali.type.function.set_lore", "Set Lore:");
        TRANSLATION_MAP.put("ali.type.function.fill_player_head", "Fill Player Head:");
        TRANSLATION_MAP.put("ali.type.function.copy_state", "Copy State:");
        TRANSLATION_MAP.put("ali.type.function.set_banner_pattern", "Set Banner Pattern:");
        TRANSLATION_MAP.put("ali.type.function.set_potion", "Set Potion:");
        TRANSLATION_MAP.put("ali.type.function.set_instrument", "Set Instrument:");
        TRANSLATION_MAP.put("ali.type.function.reference", "Reference:");
        TRANSLATION_MAP.put("ali.type.function.set_item", "Set Item:");
        TRANSLATION_MAP.put("ali.type.function.set_custom_data", "Set Custom Data:");
        TRANSLATION_MAP.put("ali.type.function.set_components", "Set Components:");
        TRANSLATION_MAP.put("ali.type.function.modify_contents", "Modify Contents:");
        TRANSLATION_MAP.put("ali.type.function.filtered", "Filtered:");
        TRANSLATION_MAP.put("ali.type.function.copy_custom_data", "Copy Custom Data:");
        TRANSLATION_MAP.put("ali.type.function.sequence", "Sequence Functions:");
        TRANSLATION_MAP.put("ali.type.function.copy_components", "Copy Components:");
        TRANSLATION_MAP.put("ali.type.function.set_fireworks", "Set Fireworks:");
        TRANSLATION_MAP.put("ali.type.function.set_firework_explosion", "Set Firework Explosion:");
        TRANSLATION_MAP.put("ali.type.function.set_book_cover", "Set Book Cover:");
        TRANSLATION_MAP.put("ali.type.function.set_written_book_pages", "Set Written Book Pages:");
        TRANSLATION_MAP.put("ali.type.function.set_writable_book_pages", "Set Writable Book Pages:");
        TRANSLATION_MAP.put("ali.type.function.toggle_tooltips", "Toggle Tooltips:");
        TRANSLATION_MAP.put("ali.type.function.set_ominous_bottle_amplifier", "Ominous Bottle Amplifier: %s");
        TRANSLATION_MAP.put("ali.type.function.set_custom_model_data", "Custom Model Data: %s");

        TRANSLATION_MAP.put("ali.enum.target.this", "This entity");
        TRANSLATION_MAP.put("ali.enum.target.killer", "Killer");
        TRANSLATION_MAP.put("ali.enum.target.direct_killer", "Directly killed by");
        TRANSLATION_MAP.put("ali.enum.target.killer_player", "Last damaged by player");

        TRANSLATION_MAP.put("ali.enum.name_source.this", "This entity");
        TRANSLATION_MAP.put("ali.enum.name_source.killer", "Killer");
        TRANSLATION_MAP.put("ali.enum.name_source.killer_player", "Last damaged by player");
        TRANSLATION_MAP.put("ali.enum.name_source.block_entity", "Block Entity");

        TRANSLATION_MAP.put("ali.enum.group_type.all", "Selects all entries");
        TRANSLATION_MAP.put("ali.enum.group_type.random", "Selects random entry");
        TRANSLATION_MAP.put("ali.enum.group_type.alternatives", "Selects only first successful entry");
        TRANSLATION_MAP.put("ali.enum.group_type.sequence", "Selects entries sequentially until first failed");
        TRANSLATION_MAP.put("ali.enum.group_type.dynamic", "Dynamic block-specific drops");

        TRANSLATION_MAP.put("ali.property.condition.unknown", "Unknown Condition: %s");
        TRANSLATION_MAP.put("ali.property.condition.predicate.target", "Target: %s");
        TRANSLATION_MAP.put("ali.property.condition.predicate.entity_type", "Entity Type:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.dist_to_player", "Distance:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.location", "Location:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.stepping_on_location", "Stepping on Location:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.effect", "Effects:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.nbt", "NBT: %s");
        TRANSLATION_MAP.put("ali.property.condition.predicate.flags", "Flags:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.equipment", "Equipment:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.entity_sub_type", "Entity Subtype: %s");
        TRANSLATION_MAP.put("ali.property.condition.predicate.vehicle", "Vehicle:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.passenger", "Passenger:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.targeted_entity", "Targeted Entity:");
        TRANSLATION_MAP.put("ali.property.condition.predicate.team", "Team: %s");
        TRANSLATION_MAP.put("ali.property.condition.random_chance.probability", "Probability: %s");
        TRANSLATION_MAP.put("ali.property.condition.random_chance_with_looting.percent", "Percent: %s");
        TRANSLATION_MAP.put("ali.property.condition.random_chance_with_looting.multiplier", "Multiplier: %s");
        TRANSLATION_MAP.put("ali.property.condition.table_bonus.location", "Location: %s");
        TRANSLATION_MAP.put("ali.property.condition.table_bonus.values", "Values: %s");
        TRANSLATION_MAP.put("ali.property.condition.dist_predicate.horizontal", "Hor.: %s");
        TRANSLATION_MAP.put("ali.property.condition.dist_predicate.absolute", "Abs.: %s");
        TRANSLATION_MAP.put("ali.property.condition.dist_predicate.x", "X: %s");
        TRANSLATION_MAP.put("ali.property.condition.dist_predicate.y", "Y: %s");
        TRANSLATION_MAP.put("ali.property.condition.dist_predicate.z", "Z: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.x", "X: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.y", "Y: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.z", "Z: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.biome", "Biome: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.structure", "Structure: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.dimension", "Dimension: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.smokey", "Above Campfire: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.light", "Light Level: %s");
        TRANSLATION_MAP.put("ali.property.condition.location.block", "Block:");
        TRANSLATION_MAP.put("ali.property.condition.location.fluid", "Fluid:");
        TRANSLATION_MAP.put("ali.property.condition.block.tag", "Tag: %s");
        TRANSLATION_MAP.put("ali.property.condition.block.blocks", "Blocks:");
        TRANSLATION_MAP.put("ali.property.condition.block.state", "Block States:");
        TRANSLATION_MAP.put("ali.property.condition.block.nbt", "NBT: %s");
        TRANSLATION_MAP.put("ali.property.condition.fluid.tag", "Tag: %s");
        TRANSLATION_MAP.put("ali.property.condition.fluid.fluid", "Fluid: %s");
        TRANSLATION_MAP.put("ali.property.condition.fluid.state", "Fluid States:");
        TRANSLATION_MAP.put("ali.property.condition.effect.amplifier", "Amplifier: %s");
        TRANSLATION_MAP.put("ali.property.condition.effect.duration", "Duration: %s");
        TRANSLATION_MAP.put("ali.property.condition.effect.ambient", "Ambient: %s");
        TRANSLATION_MAP.put("ali.property.condition.effect.visible", "Visible: %s");
        TRANSLATION_MAP.put("ali.property.condition.flags.on_fire", "On Fire: %s");
        TRANSLATION_MAP.put("ali.property.condition.flags.is_baby", "Is Baby: %s");
        TRANSLATION_MAP.put("ali.property.condition.flags.is_crouching", "Is Crouching: %s");
        TRANSLATION_MAP.put("ali.property.condition.flags.is_sprinting", "Is Sprinting: %s");
        TRANSLATION_MAP.put("ali.property.condition.flags.is_swimming", "Is Swimming: %s");
        TRANSLATION_MAP.put("ali.property.condition.equipment.head", "Head:");
        TRANSLATION_MAP.put("ali.property.condition.equipment.chest", "Chest:");
        TRANSLATION_MAP.put("ali.property.condition.equipment.legs", "Legs:");
        TRANSLATION_MAP.put("ali.property.condition.equipment.feet", "Feet:");
        TRANSLATION_MAP.put("ali.property.condition.equipment.mainhand", "Mainhand:");
        TRANSLATION_MAP.put("ali.property.condition.equipment.offhand", "Offhand:");
        TRANSLATION_MAP.put("ali.property.condition.item.items", "Items:");
        TRANSLATION_MAP.put("ali.property.condition.item.count", "Count: %s");
        TRANSLATION_MAP.put("ali.property.condition.item.components", "Components:");
        TRANSLATION_MAP.put("ali.property.condition.item.sub_predicates", "Sub Predicates:");
        TRANSLATION_MAP.put("ali.property.condition.item.sub_predicate", "Sub Predicate:");
        TRANSLATION_MAP.put("ali.property.condition.enchantment.level", "Level: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.variant", "Variant: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.blocks_on_fire", "Blocks on Fire: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.stuck_entity", "Stuck Entity:");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.in_open_water", "In Open Water: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.level", "Level: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.game_type", "Game Type: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.stats", "Stats:");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.recipes", "Recipes:");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.advancements", "Advancements:");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.advancement.done", "Done: %s");
        TRANSLATION_MAP.put("ali.property.condition.sub_entity.size", "Size: %s");
        TRANSLATION_MAP.put("ali.property.condition.scores.score", "Score:");
        TRANSLATION_MAP.put("ali.property.condition.damage_source.direct_entity", "Direct Entity:");
        TRANSLATION_MAP.put("ali.property.condition.damage_source.source_entity", "Source Entity:");
        TRANSLATION_MAP.put("ali.property.condition.damage_source.tags", "Tags:");
        TRANSLATION_MAP.put("ali.property.condition.location_check.location", "Location:");
        TRANSLATION_MAP.put("ali.property.condition.location_check.offset", "Offset:");
        TRANSLATION_MAP.put("ali.property.condition.location_check.x", "X: %s");
        TRANSLATION_MAP.put("ali.property.condition.location_check.y", "Y: %s");
        TRANSLATION_MAP.put("ali.property.condition.location_check.z", "Z: %s");
        TRANSLATION_MAP.put("ali.property.condition.weather_check.is_raining", "Is Raining: %s");
        TRANSLATION_MAP.put("ali.property.condition.weather_check.is_thundering", "Is Thundering: %s");
        TRANSLATION_MAP.put("ali.property.condition.time_check.period", "Period: %s");
        TRANSLATION_MAP.put("ali.property.condition.time_check.value", "Value: %s");
        TRANSLATION_MAP.put("ali.property.condition.value_check.provider", "Provider: %s");
        TRANSLATION_MAP.put("ali.property.condition.value_check.range", "Range: %s");
        TRANSLATION_MAP.put("ali.property.function.conditions", "Conditions:");

        TRANSLATION_MAP.put("ali.property.function.unknown", "Unknown Function: %s");
        TRANSLATION_MAP.put("ali.property.function.apply_bonus.enchantment", "Enchantment: %s");
        TRANSLATION_MAP.put("ali.property.function.apply_bonus.formula", "Formula: %s");
        TRANSLATION_MAP.put("ali.property.function.apply_bonus.formula.binomial.extra_rounds", "Extra Rounds: %s");
        TRANSLATION_MAP.put("ali.property.function.apply_bonus.formula.binomial.probability", "Probability: %s");
        TRANSLATION_MAP.put("ali.property.function.apply_bonus.formula.uniform.bonus_multiplier", "Bonus Multiplier: %s");
        TRANSLATION_MAP.put("ali.property.function.limit_count.min", "Min: %s");
        TRANSLATION_MAP.put("ali.property.function.limit_count.max", "Max: %s");
        TRANSLATION_MAP.put("ali.property.function.looting_enchant.value", "Value: %s");
        TRANSLATION_MAP.put("ali.property.function.looting_enchant.limit", "Limit: %s");
        TRANSLATION_MAP.put("ali.property.function.set_count.count", "Count: %s");
        TRANSLATION_MAP.put("ali.property.function.set_count.add", "Add: %s");
        TRANSLATION_MAP.put("ali.property.function.enchant_with_levels.levels", "Levels: %s");
        TRANSLATION_MAP.put("ali.property.function.enchant_with_levels.treasure", "Treasure: %s");
        TRANSLATION_MAP.put("ali.property.function.enchant_randomly.enchantments", "Available Enchantments:");
        TRANSLATION_MAP.put("ali.property.function.set_enchantments.enchantments", "Available Enchantments:");
        TRANSLATION_MAP.put("ali.property.function.set_enchantments.enchantment", "%s [%s]");
        TRANSLATION_MAP.put("ali.property.function.set_enchantments.add", "Add: %s");
        TRANSLATION_MAP.put("ali.property.function.set_damage.damage", "Damage: %s");
        TRANSLATION_MAP.put("ali.property.function.set_damage.add", "Add: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.name", "Name: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.attribute", "Attribute: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.operation", "Operation: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.amount", "Amount: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.id", "Id: %s");
        TRANSLATION_MAP.put("ali.property.function.set_attributes.slots", "Slots:");
        TRANSLATION_MAP.put("ali.property.function.set_name.name", "Name: %s");
        TRANSLATION_MAP.put("ali.property.function.set_name.resolution_context", "Entity: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.destination", "Destination: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration", "Map Decoration:");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration.asset_id", "Asset Id: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration.show_on_item_frame", "Show on Item Frame: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration.map_color", "Map Color: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration.exploration_map_element", "Exploration Map Element: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.map_decoration.track_count", "Track Count: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.zoom", "Zoom: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.search_radius", "Search Radius: %s");
        TRANSLATION_MAP.put("ali.property.function.exploration_map.skip_known_structures", "Skip Known Structures: %s");
        TRANSLATION_MAP.put("ali.property.function.set_stew_effect.effect", "%s: %s");
        TRANSLATION_MAP.put("ali.property.function.copy_name.source", "Source: %s");
        TRANSLATION_MAP.put("ali.property.function.set_contents.type", "Type: %s");
        TRANSLATION_MAP.put("ali.property.function.set_loot_table.name", "Name: %s");
        TRANSLATION_MAP.put("ali.property.function.set_loot_table.seed", "Seed: %s");
        TRANSLATION_MAP.put("ali.property.function.set_loot_table.type", "Type: %s");
        TRANSLATION_MAP.put("ali.property.function.set_lore.replace", "Replace: %s");
        TRANSLATION_MAP.put("ali.property.function.set_lore.resolution_context", "Entity: %s");
        TRANSLATION_MAP.put("ali.property.function.set_lore.lore", "Lore:");
        TRANSLATION_MAP.put("ali.property.function.fill_player_head.target", "Target: %s");
        TRANSLATION_MAP.put("ali.property.function.copy_state.block", "Block: %s");
        TRANSLATION_MAP.put("ali.property.function.copy_state.properties", "Properties:");
        TRANSLATION_MAP.put("ali.property.function.set_banner_pattern.append", "Append: %s");
        TRANSLATION_MAP.put("ali.property.function.set_banner_pattern.patterns", "Patterns:");
        TRANSLATION_MAP.put("ali.property.function.set_banner_pattern.color", "Color: %s");
        TRANSLATION_MAP.put("ali.property.function.set_potion.name", "Name: %s");
        TRANSLATION_MAP.put("ali.property.function.set_potion.effects", "Effects:");
        TRANSLATION_MAP.put("ali.property.function.set_instrument.options", "Options: %s");
        TRANSLATION_MAP.put("ali.property.function.reference.name", "Name: %s");
        TRANSLATION_MAP.put("ali.property.function.modify_contents.component", "Component: %s");
        TRANSLATION_MAP.put("ali.property.function.modify_contents.modifier", "Modifier:");
        TRANSLATION_MAP.put("ali.property.function.filtered.filter", "Filter:");
        TRANSLATION_MAP.put("ali.property.function.filtered.modifier", "Modifier:");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.source", "Source:");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.operations", "Operations:");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.operation", "Operation:");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.operation.source", "Source: %s");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.operation.target", "Target: %s");
        TRANSLATION_MAP.put("ali.property.function.copy_custom_data.operation.operation", "Merge Strategy: %s");
        TRANSLATION_MAP.put("ali.property.function.sequence.function", "Functions:");
        TRANSLATION_MAP.put("ali.property.function.copy_components.source", "Source:");
        TRANSLATION_MAP.put("ali.property.function.copy_components.include", "Include Components:");
        TRANSLATION_MAP.put("ali.property.function.copy_components.exclude", "Exclude Components:");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions", "Explosion:");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.operation", "Operation: %s");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.list", "List:");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion", "Explosion:");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion.shape", "Shape: %s");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion.colors", "Colors: %s");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion.fade_colors", "Fade Colors: %s");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion.has_trails", "Has Trails: %s");
        TRANSLATION_MAP.put("ali.property.function.set_fireworks.explosions.explosion.has_twinkle", "Has Twinkle: %s");
        TRANSLATION_MAP.put("ali.property.function.set_firework_explosion.shape", "Shape: %s");
        TRANSLATION_MAP.put("ali.property.function.set_firework_explosion.colors", "Colors: %s");
        TRANSLATION_MAP.put("ali.property.function.set_firework_explosion.fade_colors", "Fade Colors: %s");
        TRANSLATION_MAP.put("ali.property.function.set_firework_explosion.has_trails", "Has Trails: %s");
        TRANSLATION_MAP.put("ali.property.function.set_firework_explosion.has_twinkle", "Has Twinkle: %s");
        TRANSLATION_MAP.put("ali.property.function.set_book_cover.author", "Author: %s");
        TRANSLATION_MAP.put("ali.property.function.set_book_cover.title", "Title: %s");
        TRANSLATION_MAP.put("ali.property.function.set_book_cover.title.filtered", "Filtered: %s");
        TRANSLATION_MAP.put("ali.property.function.set_book_cover.generation", "Generation: %s");
        TRANSLATION_MAP.put("ali.property.function.set_written_book_pages.pages", "Pages:");
        TRANSLATION_MAP.put("ali.property.function.set_written_book_pages.pages.page", "Page: %s");
        TRANSLATION_MAP.put("ali.property.function.set_written_book_pages.pages.page.filtered", "Filtered: %s");
        TRANSLATION_MAP.put("ali.property.function.set_written_book_pages.page_operation", "Page Operation: %s");
        TRANSLATION_MAP.put("ali.property.function.set_writable_book_pages.pages", "Pages:");
        TRANSLATION_MAP.put("ali.property.function.set_writable_book_pages.pages.page", "Page: %s");
        TRANSLATION_MAP.put("ali.property.function.set_writable_book_pages.pages.page.filtered", "Filtered: %s");
        TRANSLATION_MAP.put("ali.property.function.set_writable_book_pages.page_operation", "Page Operation: %s");

        TRANSLATION_MAP.put("ali.util.advanced_loot_info.two_values", "%s%s");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.two_values_with_space", "%s %s");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.1", "  ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.2", "    ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.3", "      ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.4", "        ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.5", "          ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.6", "            ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.7", "              ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.pad.8", "                ->");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.key_value", "%s: %s");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.delimiter.functions", "----- Functions -----");
        TRANSLATION_MAP.put("ali.util.advanced_loot_info.delimiter.conditions", "----- Conditions -----");

        TRANSLATION_MAP.put("ali/loot_table/chests/ancient_city_ice_box", "Ancient City Ice Box Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/simple_dungeon", "Simple Dungeon Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_mason", "Village Mason Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_temple", "Village Temple Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/bastion_treasure", "Bastion Treasure Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/ruined_portal", "Ruined Portal Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_fisher", "Village Fisher Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_toolsmith", "Village Toolsmith Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/shipwreck_map", "Shipwreck Map Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/shipwreck_supply", "Shipwreck Supply Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_snowy_house", "Village Snowy House Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/stronghold_crossing", "Stronghold Crossing Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/nether_bridge", "Nether Bridge Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/abandoned_mineshaft", "Abandoned Mineshaft Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/shipwreck_treasure", "Shipwreck Treasure Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/stronghold_corridor", "Stronghold Corridor Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_fletcher", "Village Fletcher Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_tannery", "Village Tannery Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/spawn_bonus_chest", "Spawn Bonus Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_plains_house", "Village Plains House Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/underwater_ruin_small", "Underwater Ruin Small Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/buried_treasure", "Buried Treasure Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_armorer", "Village Armorer Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/bastion_hoglin_stable", "Bastion Hoglin Stable Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/desert_pyramid", "Desert Pyramid Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/underwater_ruin_big", "Underwater Ruin Big Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/igloo_chest", "Igloo Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/ancient_city", "Ancient City Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/bastion_bridge", "Bastion Bridge Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/pillager_outpost", "Pillager Outpost Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_shepherd", "Village Shepherd Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_cartographer", "Village Cartographer Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/jungle_temple_dispenser", "Jungle Temple Dispenser Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/jungle_temple", "Jungle Temple Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_savanna_house", "Village Savanna House Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_taiga_house", "Village Taiga House Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_butcher", "Village Butcher Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_desert_house", "Village Desert House Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/end_city_treasure", "End City Treasure Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/stronghold_library", "Stronghold Library Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/village/village_weaponsmith", "Village Weaponsmith Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/bastion_other", "Bastion Other Chest");
        TRANSLATION_MAP.put("ali/loot_table/chests/woodland_mansion", "Woodland Mansion Chest");

        TRANSLATION_MAP.put("ali/loot_table/archaeology/trail_ruins_common", "Trail Ruins Common");
        TRANSLATION_MAP.put("ali/loot_table/archaeology/ocean_ruin_warm", "Ocean Ruins Warm");
        TRANSLATION_MAP.put("ali/loot_table/archaeology/trail_ruins_rare", "Trail Ruins Rare");
        TRANSLATION_MAP.put("ali/loot_table/archaeology/ocean_ruin_cold", "Ocean Ruin Cold");
        TRANSLATION_MAP.put("ali/loot_table/archaeology/desert_well", "Desert Well");
        TRANSLATION_MAP.put("ali/loot_table/archaeology/desert_pyramid", "Desert Pyramid");

        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/fisherman_gift", "Fisherman Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/farmer_gift", "Farmer Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/mason_gift", "Mason Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/leatherworker_gift", "Leatherworker Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/armorer_gift", "Armorer Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/fletcher_gift", "Fletcher Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/toolsmith_gift", "Toolsmith Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/cartographer_gift", "Cartographer Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/butcher_gift", "Butcher Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/shepherd_gift", "Shepherd Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/weaponsmith_gift", "Weaponsmith Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/cleric_gift", "Cleric Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/hero_of_the_village/librarian_gift", "Librarian Gift");

        TRANSLATION_MAP.put("ali/loot_table/gameplay/fishing", "Fishing");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/fishing/junk", "Fishing: Junk");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/fishing/fish", "Fishing: Fish");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/fishing/treasure", "Fishing: Treasure");

        TRANSLATION_MAP.put("ali/loot_table/gameplay/sniffer_digging", "Sniffer Digging");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/cat_morning_gift", "Cat Morning Gift");
        TRANSLATION_MAP.put("ali/loot_table/gameplay/piglin_bartering", "Piglin Bartering");
    }
}
